init linearb buildkite plugin

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -1,30 +1,52 @@
 #!/bin/bash
+set -e
 
-app_id=$BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_APP_ID
-description="${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_DESCRIPTION:-${BUILDKITE_MESSAGE:-}}"
-user="${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_USER:-${BUILDKITE_BUILD_CREATOR_EMAIL:-}}"
-revision="${BUILDKITE_BUILD_NUMBER:-}"
-api_key="${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_API_KEY:-${NEW_RELIC_API_KEY:-}}"
+record_deploy_time() {
 
-echo "--- :newrelic: Creating deploment marker for $app_id"
+  # Convert buildkite repo to url (git@github.com:org/repo.git -> https://github.com/org/repo.git)
+  tmp1=${BUILDKITE_REPO:-}
+  tmp2=${tmp1/:/\/}
+  repo_url=${tmp2/git@/https:\/\/}
+  
+  # user provided repo takes precendence over BUILDKITE_REPO
+  repo="${BUILDKITE_PLUGIN_LINEARB_DEPLOY_TIME_REPO:-${repo_url:-}}"
 
-if [ -z $api_key ]; then
-  ssm_param_name=${BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_API_KEY_SSM_PARAM_NAME:-"NEWRELIC_API_KEY"}
-  api_key=$(aws ssm get-parameter --with-decryption --name "$ssm_param_name" --query=Parameter.Value --output=text)
-else
-  api_key=$BUILDKITE_PLUGIN_NEWRELIC_DEPLOY_MARKER_API_KEY
-fi
+  # api can be provided, if it is not we try to retrieve from parameter store
+  api_key="${BUILDKITE_PLUGIN_LINEARB_DEPLOY_TIME_API_KEY:-}"
+  
+  # git commit sha
+  sha="${BUILDKITE_PLUGIN_LINEARB_DEPLOY_TIME_COMMIT:-${BUILDKITE_COMMIT:-}}"
 
-curl -X POST "https://api.newrelic.com/v2/applications/${app_id}/deployments.json" \
-   -H "X-Api-Key:${api_key}" -i \
-   -H "Content-Type: application/json" \
-   -d \
-  '{
-    "deployment": {
-      "revision": "'"${revision}"'",
-      "description": "'"${description}"'",
-      "user": "'"${user}"'"
-    } 
-  }' 
+  echo "--- :linearb: deploy time being recorded for repo: ${repo} sha: ${sha}"
 
+  # If the api key is provided use it, otherwise try to retrieve it from parameter store
+  if [ -z "$api_key" ]; then
+    ssm_param_name=${BUILDKITE_PLUGIN_LINEARB_DEPLOY_TIME_API_KEY_SSM_PARAM_NAME:-"/infrastructure/linearb-api-token"}
+    api_key=$(aws ssm get-parameter --with-decryption --name "$ssm_param_name" --query=Parameter.Value --output=text)
+  else
+    api_key=$BUILDKITE_PLUGIN_LINEARB_DEPLOY_TIME_API_KEY
+  fi
 
+  event_time=$(date +%s)
+
+  json=$(jq -n \
+    --argjson event_time "$event_time" \
+    --arg stage_id "release" \
+    --arg repo_url "$repo" \
+    --arg sha "$sha" \
+    '{event_time: $event_time, repo_url: $repo_url, stage_id: $stage_id, head_sha: $sha}')  
+
+  status_code=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+    -X POST "https://public-api.linearb.io/api/v1/cycle-time-stages" \
+    -H "X-Api-Key:${api_key}" -i \
+    -H "Content-Type: application/json" \
+    -d "$json" \
+  )
+
+  if [[ $status_code -lt 200 ]] && [[ $status_code -gt 299 ]]; then
+    echo "--- :linearb: Deploy time recording failed with status code ${status_code}"
+    exit 1
+  fi
+}
+
+record_deploy_time
